"""create FAQ documents

Revision ID: 87d4cca3dc93
Revises: 
Create Date: 2026-08-13 22:16:11.119711

"""
from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '87d4cca3dc93'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faq_id', sa.String(length=100), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('embedding', VECTOR(dim=1536), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faq_id'),
    schema='ai'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faq_documents', schema='ai')
    # ### end Alembic commands ###
